In [1]:
import pandas as pd

In [2]:
def preprocessing(df):
    df = df.apply(pd.to_numeric, errors = 'coerce')
    
    for elements in ['CO','CO2',"NO2",'PM10','PM2.5']:
#         print(elements)
        for years in [2015, 2016, 2017,2018,2019]:
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].mean()) # 평균
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].std())  # 표준편차
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].min())  # 최소값
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].max())  # 최대값
        print()

In [3]:
s1w = pd.read_csv('excel/서면1w.csv', encoding = 'cp949')
s1w

,Unnamed: 0,datetime-year,month,day,hour,CO,CO2,NO2,PM2.5,PM10
0,0.0,2019,1,1,0,0.5,501.0,0.033,22.0,30.0
1,1.0,2019,1,1,1,0.5,494.0,0.028,18.0,31.0
2,2.0,2019,1,1,2,0.5,429.0,0.027,24.0,23.0
3,3.0,2019,1,1,3,0.5,428.0,0.027,18.0,19.0
4,4.0,2019,1,1,4,0.5,431.0,0.031,15.0,25.0
...,...,...,...,...,...,...,...,...,...,...
52579,NaN,2014,12,31,19,0.5,639.0,0.044,29.0,47.0
52580,NaN,2014,12,31,20,0.5,643.0,0.043,23.0,40.0
52581,NaN,2014,12,31,21,0.5,618.0,0.042,33.0,50.0
52582,NaN,2014,12,31,22,0.5,613.0,0.041,32.0,49.0
52583,NaN,2014,12,31,23,0.4,559.0,0.034,26.0,42.0

In [4]:
preprocessing(s1w)

0.5219979115906858
0.18677845492267314
0.1
1.9
0.607540144286708
0.18381864283581378
0.1
2.4
0.5319682650799175
0.16703212589636238
0.1
1.9
0.378013087447961
0.1670205416205621
0.1
1.5
0.47955103472469623
0.1738296008120934
0.1
1.5

598.1996277338297
119.95034140185284
364.0
1135.0
639.2935909519322
156.47964679134594
307.0
1384.0
612.0683302238806
141.4994899324225
381.0
1151.0
576.8709526044111
122.49879188147548
371.0
1125.0
559.5023851076207
133.6311560316607
316.0
1205.0

0.03647034930950421
0.01325423091754042
0.004
0.115
0.037911009497009644
0.017278630210121288
0.001
0.18600000000000003
0.04172076483618941
0.015158545782358314
0.005
0.168
0.03947219524040742
0.016683389179797913
0.001
0.121
0.03768074953445029
0.012708790751004126
0.003
0.145

51.88850913376547
22.323794106615072
2.0
383.0
47.419878296146045
19.350169278507625
2.0
288.0
45.11030103480715
18.72018477056826
7.0
346.0
39.09887881679389
25.221081458842956
4.0
985.0
41.61535756154748
18.174229370752183
3.0
334.0

30.055125498475252
16.216150274893206
4.0
897.0
27.069504880630365
30.314768197295276
1.0
983.0
28.630709768095574
30.341140754610105
1.0
935.0
24.423923331755798
39.8184587046665
1.0
985.0
20.69690915501234
11.865882557393784
1.0
108.0

In [5]:
s1w = s1w.loc[s1w['datetime-year']>=2015]
print(((((s1w['CO']==0)).sum())+(s1w['CO'].isnull().sum())) / 43824)
print(((((s1w['CO2']==0)).sum())+(s1w['CO2'].isnull().sum())) / 43824)
print(((((s1w['NO2']==0)).sum())+(s1w['NO2'].isnull().sum())) / 43824)
print(((((s1w['PM10']==0)).sum())+(s1w['PM10'].isnull().sum())) / 43824)
print(((((s1w['PM2.5']==0)).sum())+(s1w['PM2.5'].isnull().sum())) / 43824)

0.02468966776195692
0.02384538152610442
0.029048010222709017
0.03509492515516612
0.02955001825483753

In [7]:
# 파일 바꿨음 hour column => 0 -> 24로 
# because, pandas doesn't cognize and(&) grammar.

s1w = pd.read_csv('excel/서면1w_.csv', encoding = 'cp949')
s1w = s1w.loc[s1w['datetime-year']>=2015]
s1w = s1w.drop(['Unnamed: 0'], axis = 1)

# s1p = s1p.loc[(s1p['hour']>=5) & (s1p['hour']== 0)]

s1w_non = s1w.loc[((s1w['hour']<5))]
s1w_non
s1w_op = s1w.loc[((s1w['hour']>=5))]
s1w_op

       datetime-year  month  day  hour   CO    CO2    NO2  PM2.5  PM10
0               2019      1    1    24  0.5  501.0  0.033   22.0  30.0
5               2019      1    1     5  0.4  472.0  0.025   19.0  29.0
6               2019      1    1     6  0.4  480.0  0.026   14.0  25.0
7               2019      1    1     7  0.4  465.0  0.030   20.0  37.0
8               2019      1    1     8  0.4  474.0  0.032   14.0  33.0
...              ...    ...  ...   ...  ...    ...    ...    ...   ...
43819           2015     12   31    19  0.7  844.0  0.033   50.0  88.0
43820           2015     12   31    20  0.7  789.0  0.032   45.0  73.0
43821           2015     12   31    21  0.8  746.0  0.035   52.0  80.0
43822           2015     12   31    22  0.8  679.0  0.036   48.0  82.0
43823           2015     12   31    23  0.7  606.0  0.031   47.0  65.0

[36520 rows x 9 columns]

In [8]:
def preprocessing(df,df2):
    df = df.apply(pd.to_numeric, errors = 'coerce')
    df2 = df2.apply(pd.to_numeric, errors = 'coerce')
    
    for elements in ['CO','CO2',"NO2",'PM10','PM2.5']:
        for years in [2015, 2016, 2017,2018,2019]:
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].mean()) # 평균
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].std())  # 표준편차
            print(df2[elements].loc[(df2['datetime-year']==years) & (df2[elements]>0)].mean()) # 평균
            print(df2[elements].loc[(df2['datetime-year']==years) & (df2[elements]>0)].std())  # 표준편차
        print()
preprocessing(s1w_non,s1w_op)

0.45239749826268066
0.17887227599687217
0.5359470752089288
0.1852147606862536
0.5358126721763055
0.17680396587158329
0.6221226547185595
0.18179449848646081
0.4722067039106133
0.16095849089161748
0.5439557360974909
0.1656586783244485
0.33199713672154474
0.15407485247020566
0.3871860730593692
0.16799309407707985
0.43555078683833715
0.1726941883010726
0.4881481481481854
0.17275860551358305

452.3008356545961
34.410536825184295
627.4608938547486
109.13603942470205
466.2759831460674
66.34748777958133
674.1714326160816
145.88943202370814
439.8212290502793
31.174608396755126
646.5949048152296
129.23301872266393
445.1265103056148
25.977606632409813
602.9162568497962
117.1724682199381
402.7873399715505
43.40704810713037
590.1521769369871
123.44414673062562

0.025910229645093978
0.010189069858682375
0.03858384401114176
0.012778233850163719
0.02756041666666659
0.013248224703075625
0.04001354210748996
0.01724485356849966
0.03026885474860329
0.014401779214025972
0.04401595521343558
0.014238609035886446
0.028055964653902768
0.01488911970353791
0.04172622855481204
0.016085290921496704
0.028426837972876384
0.012687191259923196
0.03948366013071852
0.011904007752241172

47.393478260869564
31.66772904053487
52.761576354679804
19.894832271681953
39.41184767277856
23.22637941538506
49.0506965388482
18.03250083839995
36.34375
25.148254442257763
46.84977452085682
16.62216126718431
34.67511177347243
50.03122327667203
39.94191990911673
16.61828759639181
30.378057820607857
16.27985024864533
43.72636123102632
17.731898847658417

28.74927536231884
28.14135109130187
30.307304785894207
12.66943754956302
23.90356394129979
20.44687285789841
27.71012443438914
31.905761557682112
27.89061397318278
49.86422274399636
28.77798062069934
24.68140246092971
30.622890682318417
91.16865720810937
23.23204965439413
16.865418349566436
18.0440956651719
12.06726344030564
21.191883977130107
11.762728454911066