In [1]:
import pandas as pd

In [2]:
def preprocessing(df):
    df = df.apply(pd.to_numeric, errors = 'coerce')
    
    for elements in ['CO','CO2',"NO2",'PM10','PM2.5']:
#         print(elements)
        for years in [2015, 2016, 2017,2018,2019]:
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].mean()) # 평균
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].std())  # 표준편차
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].min())  # 최소값
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].max())  # 최대값
        print()

In [3]:
s1w = pd.read_csv('excel/서면1w.csv', encoding = 'cp949')
s1w

,Unnamed: 0,datetime-year,month,day,hour,CO,CO2,NO2,PM2.5,PM10
0,0.0,2019,1,1,0,0.5,501.0,0.033,22.0,30.0
1,1.0,2019,1,1,1,0.5,494.0,0.028,18.0,31.0
2,2.0,2019,1,1,2,0.5,429.0,0.027,24.0,23.0
3,3.0,2019,1,1,3,0.5,428.0,0.027,18.0,19.0
4,4.0,2019,1,1,4,0.5,431.0,0.031,15.0,25.0
...,...,...,...,...,...,...,...,...,...,...
52579,NaN,2014,12,31,19,0.5,639.0,0.044,29.0,47.0
52580,NaN,2014,12,31,20,0.5,643.0,0.043,23.0,40.0
52581,NaN,2014,12,31,21,0.5,618.0,0.042,33.0,50.0
52582,NaN,2014,12,31,22,0.5,613.0,0.041,32.0,49.0
52583,NaN,2014,12,31,23,0.4,559.0,0.034,26.0,42.0

In [4]:
preprocessing(s1w)

0.5219979115906858
0.18677845492267314
0.1
1.9
0.607540144286708
0.18381864283581378
0.1
2.4
0.5319682650799175
0.16703212589636238
0.1
1.9
0.378013087447961
0.1670205416205621
0.1
1.5
0.47955103472469623
0.1738296008120934
0.1
1.5

598.1996277338297
119.95034140185284
364.0
1135.0
639.2935909519322
156.47964679134594
307.0
1384.0
612.0683302238806
141.4994899324225
381.0
1151.0
576.8709526044111
122.49879188147548
371.0
1125.0
559.5023851076207
133.6311560316607
316.0
1205.0

0.03647034930950421
0.01325423091754042
0.004
0.115
0.037911009497009644
0.017278630210121288
0.001
0.18600000000000003
0.04172076483618941
0.015158545782358314
0.005
0.168
0.03947219524040742
0.016683389179797913
0.001
0.121
0.03768074953445029
0.012708790751004126
0.003
0.145

51.88850913376547
22.323794106615072
2.0
383.0
47.419878296146045
19.350169278507625
2.0
288.0
45.11030103480715
18.72018477056826
7.0
346.0
39.09887881679389
25.221081458842956
4.0
985.0
41.61535756154748
18.174229370752183
3.0
334.0

30.055125498475252
16.216150274893206
4.0
897.0
27.069504880630365
30.314768197295276
1.0
983.0
28.630709768095574
30.341140754610105
1.0
935.0
24.423923331755798
39.8184587046665
1.0
985.0
20.69690915501234
11.865882557393784
1.0
108.0

In [5]:
s1w = s1w.loc[s1w['datetime-year']>=2015]
print(((((s1w['CO']==0)).sum())+(s1w['CO'].isnull().sum())) / 43824)
print(((((s1w['CO2']==0)).sum())+(s1w['CO2'].isnull().sum())) / 43824)
print(((((s1w['NO2']==0)).sum())+(s1w['NO2'].isnull().sum())) / 43824)
print(((((s1w['PM10']==0)).sum())+(s1w['PM10'].isnull().sum())) / 43824)
print(((((s1w['PM2.5']==0)).sum())+(s1w['PM2.5'].isnull().sum())) / 43824)

0.02468966776195692
0.02384538152610442
0.029048010222709017
0.03509492515516612
0.02955001825483753