In [1]:
import pandas as pd

In [2]:
def preprocessing(df):
    df = df.apply(pd.to_numeric, errors = 'coerce')
    
    for elements in ['CO','CO2',"NO2",'PM10','PM2.5']:
#         print(elements)
        for years in [2015, 2016, 2017,2018,2019]:
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].mean()) # 평균
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].std())  # 표준편차
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].min())  # 최소값
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].max())  # 최대값
        print()

In [3]:
s2p = pd.read_csv('excel/서면2p.csv', encoding = 'cp949')
s2p

,Unnamed: 0,datetime-year,month,day,hour,CO,CO2,NO2,PM2.5,PM10
0,0.0,2019,1,1,0,0.5,527.0,0.035,18.0,17.0
1,1.0,2019,1,1,1,0.4,502.0,0.031,23.0,35.0
2,2.0,2019,1,1,2,0.4,457.0,0.030,17.0,31.0
3,3.0,2019,1,1,3,0.4,456.0,0.028,16.0,21.0
4,4.0,2019,1,1,4,0.4,453.0,0.033,17.0,31.0
...,...,...,...,...,...,...,...,...,...,...
52579,NaN,2014,12,31,19,0.4,650.0,0.051,10.0,38.0
52580,NaN,2014,12,31,20,0.4,650.0,0.048,20.0,39.0
52581,NaN,2014,12,31,21,0.4,597.0,0.045,10.0,37.0
52582,NaN,2014,12,31,22,0.4,569.0,0.043,10.0,34.0
52583,NaN,2014,12,31,23,0.3,561.0,0.036,11.0,32.0

In [4]:
preprocessing(s2p)

0.4530127462340889
0.1694190781316821
0.1
2.5
0.48439740920658364
0.18458375805171073
0.1
4.3
0.4741475295755128
0.18980740559069775
0.1
1.7
0.46529616724739764
0.2090780071002906
0.1
1.9
0.4655288127748352
0.16420193890989532
0.1
1.7

548.6497919556172
92.17409564609444
348.0
1162.0
539.4859228362878
98.41284857543026
351.0
1164.0
536.5349106935746
80.45187381853948
385.0
1206.0
546.0962833914053
85.14011135824383
387.0
1154.0
538.7981948623004
93.67193022313468
309.0
1295.0

0.0430541237113398
0.018925689464743694
0.003
0.128
0.047695359628769876
0.021736084360157854
0.001
0.243
0.04646289629543546
0.021220639744030195
0.002
0.23800000000000002
0.04433387565368937
0.01946530659321608
0.001
0.193
0.038106890561666974
0.017229219286480787
0.004
0.166

46.01655204569297
41.17259144182189
5.0
1620.0
39.96815583809635
19.684789467192296
4.0
335.0
37.12778880971849
21.684947293927966
3.0
973.0
32.947064371610466
23.03728140174261
2.0
956.0
34.61426730701652
20.403557350589942
3.0
273.0

23.559139784946236
23.969969962477663
1.0
980.0
30.213030831879
31.830232672030913
1.0
985.0
25.0746550300743
16.490433233373246
1.0
960.0
22.901290547610742
18.41232270529894
1.0
948.0
19.13008695652174
10.877928040952558
1.0
87.0

In [5]:
s2p = s2p.loc[s2p['datetime-year']>=2015]
print(((((s2p['CO']==0)).sum())+(s2p['CO'].isnull().sum())) / 43824)
print(((((s2p['CO2']==0)).sum())+(s2p['CO2'].isnull().sum())) / 43824)
print(((((s2p['NO2']==0)).sum())+(s2p['NO2'].isnull().sum())) / 43824)
print(((((s2p['PM10']==0)).sum())+(s2p['PM10'].isnull().sum())) / 43824)
print(((((s2p['PM2.5']==0)).sum())+(s2p['PM2.5'].isnull().sum())) / 43824)

0.015379700620664476
0.01521997079225995
0.018642752829499818
0.02489503468419131
0.024210478276743337