In [2]:
import pandas as pd

In [3]:
def preprocessing(df):
    df = df.apply(pd.to_numeric, errors = 'coerce')
    
    for elements in ['CO','CO2',"NO2",'PM10','PM2.5']:
#         print(elements)
        for years in [2015, 2016, 2017,2018,2019]:
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].mean()) # 평균
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].std())  # 표준편차
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].min())  # 최소값
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].max())  # 최대값
        print()

In [4]:
s2p = pd.read_csv('excel/서면2p.csv', encoding = 'cp949')
s2p

,Unnamed: 0,datetime-year,month,day,hour,CO,CO2,NO2,PM2.5,PM10
0,0.0,2019,1,1,0,0.5,527.0,0.035,18.0,17.0
1,1.0,2019,1,1,1,0.4,502.0,0.031,23.0,35.0
2,2.0,2019,1,1,2,0.4,457.0,0.030,17.0,31.0
3,3.0,2019,1,1,3,0.4,456.0,0.028,16.0,21.0
4,4.0,2019,1,1,4,0.4,453.0,0.033,17.0,31.0
...,...,...,...,...,...,...,...,...,...,...
52579,NaN,2014,12,31,19,0.4,650.0,0.051,10.0,38.0
52580,NaN,2014,12,31,20,0.4,650.0,0.048,20.0,39.0
52581,NaN,2014,12,31,21,0.4,597.0,0.045,10.0,37.0
52582,NaN,2014,12,31,22,0.4,569.0,0.043,10.0,34.0
52583,NaN,2014,12,31,23,0.3,561.0,0.036,11.0,32.0

In [5]:
preprocessing(s2p)

0.4530127462340889
0.1694190781316821
0.1
2.5
0.48439740920658364
0.18458375805171073
0.1
4.3
0.4741475295755128
0.18980740559069775
0.1
1.7
0.46529616724739764
0.2090780071002906
0.1
1.9
0.4655288127748352
0.16420193890989532
0.1
1.7

548.6497919556172
92.17409564609444
348.0
1162.0
539.4859228362878
98.41284857543026
351.0
1164.0
536.5349106935746
80.45187381853948
385.0
1206.0
546.0962833914053
85.14011135824383
387.0
1154.0
538.7981948623004
93.67193022313468
309.0
1295.0

0.0430541237113398
0.018925689464743694
0.003
0.128
0.047695359628769876
0.021736084360157854
0.001
0.243
0.04646289629543546
0.021220639744030195
0.002
0.23800000000000002
0.04433387565368937
0.01946530659321608
0.001
0.193
0.038106890561666974
0.017229219286480787
0.004
0.166

46.01655204569297
41.17259144182189
5.0
1620.0
39.96815583809635
19.684789467192296
4.0
335.0
37.12778880971849
21.684947293927966
3.0
973.0
32.947064371610466
23.03728140174261
2.0
956.0
34.61426730701652
20.403557350589942
3.0
273.0

23.559139784946236
23.969969962477663
1.0
980.0
30.213030831879
31.830232672030913
1.0
985.0
25.0746550300743
16.490433233373246
1.0
960.0
22.901290547610742
18.41232270529894
1.0
948.0
19.13008695652174
10.877928040952558
1.0
87.0

In [6]:
s2p = s2p.loc[s2p['datetime-year']>=2015]
print(((((s2p['CO']==0)).sum())+(s2p['CO'].isnull().sum())) / 43824)
print(((((s2p['CO2']==0)).sum())+(s2p['CO2'].isnull().sum())) / 43824)
print(((((s2p['NO2']==0)).sum())+(s2p['NO2'].isnull().sum())) / 43824)
print(((((s2p['PM10']==0)).sum())+(s2p['PM10'].isnull().sum())) / 43824)
print(((((s2p['PM2.5']==0)).sum())+(s2p['PM2.5'].isnull().sum())) / 43824)

0.015379700620664476
0.01521997079225995
0.018642752829499818
0.02489503468419131
0.024210478276743337

In [10]:
# 파일 바꿨음 hour column => 0 -> 24로 
# because, pandas doesn't cognize and(&) grammar.

s2p = pd.read_csv('excel/서면2p_.csv', encoding = 'cp949')
s2p = s2p.loc[s2p['datetime-year']>=2015]
s2p = s2p.drop(['Unnamed: 0'], axis = 1)

# s1p = s1p.loc[(s1p['hour']>=5) & (s1p['hour']== 0)]

s2p_non = s2p.loc[((s2p['hour']<5))]
s2p_non
s2p_op = s2p.loc[((s2p['hour']>=5))]
s2p_op

       datetime-year  month  day  hour   CO    CO2    NO2  PM2.5  PM10
0               2019      1    1    24  0.5  527.0  0.035   18.0  17.0
5               2019      1    1     5  0.3  486.0  0.027   22.0  28.0
6               2019      1    1     6  0.4  507.0  0.028   19.0  19.0
7               2019      1    1     7  0.3  483.0  0.032   20.0  34.0
8               2019      1    1     8  0.4  504.0  0.036   16.0  23.0
...              ...    ...  ...   ...  ...    ...    ...    ...   ...
43819           2015     12   31    19  0.6  579.0  0.059   49.0  64.0
43820           2015     12   31    20  0.7  625.0  0.060   47.0  56.0
43821           2015     12   31    21  0.8  606.0  0.068   47.0  67.0
43822           2015     12   31    22  0.8  606.0  0.071   62.0  67.0
43823           2015     12   31    23  0.7  580.0  0.048   55.0  70.0

[36520 rows x 9 columns]

In [12]:
def preprocessing(df,df2):
    df = df.apply(pd.to_numeric, errors = 'coerce')
    df2 = df2.apply(pd.to_numeric, errors = 'coerce')
    
    for elements in ['CO','CO2',"NO2",'PM10','PM2.5']:
        for years in [2015, 2016, 2017,2018,2019]:
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].mean()) # 평균
            print(df[elements].loc[(df['datetime-year']==years) & (df[elements]>0)].std())  # 표준편차
            print(df2[elements].loc[(df2['datetime-year']==years) & (df2[elements]>0)].mean()) # 평균
            print(df2[elements].loc[(df2['datetime-year']==years) & (df2[elements]>0)].std())  # 표준편차
        print()
preprocessing(s2p_non,s2p_op)

0.42328956461644623
0.1620774998450876
0.4590004176528076
0.17024382689472747
0.4475240715268196
0.1999760595745324
0.4918520578420636
0.18041444376353266
0.4310606060606055
0.1891421503628356
0.48287308228731446
0.18876108047514942
0.42849277357191917
0.20526875344095452
0.47276791951936037
0.20906726350620317
0.4328983516483501
0.1639591118169296
0.4721402727525859
0.16347074273611628

443.072852233677
34.85868778276373
569.9940252883146
85.19973487372154
435.37052341597797
28.921155902204976
560.5439476250174
94.01532400934649
444.74242424242425
28.798231848369888
555.1238493723849
74.58833318868845
454.4845147969718
34.59007188075097
564.6951236551628
80.17381617026588
431.28983516483515
28.92666030971845
560.5811299749513
86.98469554092358

0.03254577218728175
0.014628995824265788
0.04517058409570683
0.01898762804016828
0.03346662030598052
0.019362129667401338
0.050544277360066545
0.021056767788143742
0.03217002081887567
0.017767701363307405
0.04933542538354197
0.020690690158151087
0.031606896551724016
0.01610378543932551
0.04691306778476558
0.019070539598893967
0.029627922971114138
0.015152487282219879
0.03982370143433997
0.017116936855064394

47.26778242677824
92.7892778548296
45.76543037088874
17.551168440307297
33.689367616400276
21.380065379600058
41.23465096719933
19.077561238596722
31.80375782881002
22.336229418665575
38.20171252105558
21.39278265376202
30.70757363253857
33.18576167104738
33.39965986394558
20.354975115005292
29.20125786163522
17.391904670478944
35.704334365325074
20.789023678117143

25.380851063829788
51.08532838019503
23.194952502481215
12.931299668035063
30.493775933609957
51.465239681655426
30.156245628759265
26.12778655421895
23.880832735104093
13.273380430082096
25.30934236522721
17.042592339178793
22.54865424430642
14.294621421068449
22.97273489932886
19.139003422526194
18.22451790633609
10.675877830178154
19.313397462707375
10.909961335616739