In [1]:
import pandas as pd

In [2]:
def preprocessing(df):
    df = df.apply(pd.to_numeric, errors = 'coerce')
    
    for elements in ['CO','CO2',"NO2",'PM10','PM2.5','HCHO']:
#         print(elements)
        for years in [2015, 2016, 2017,2018,2019]:
            print(df[elements].loc[(df['year']==years) & (df[elements]>0)].mean()) # 평균
            print(df[elements].loc[(df['year']==years) & (df[elements]>0)].std())  # 표준편차
            print(df[elements].loc[(df['year']==years) & (df[elements]>0)].min())  # 최소값
            print(df[elements].loc[(df['year']==years) & (df[elements]>0)].max())  # 최대값
        print()

In [3]:
s2w = pd.read_csv('excel/서면2w.csv', encoding = 'cp949')
s2w

       year  month  day  hour   CO    CO2    NO2  PM2.5  PM10  HCHO
0      2019      1    1     0  0.4  525.0  0.027   18.0  25.0   2.6
1      2019      1    1     1  0.3  498.0  0.024   18.0  33.0   1.9
2      2019      1    1     2  0.3  460.0  0.024   22.0  31.0   1.8
3      2019      1    1     3  0.3  459.0  0.023   17.0  28.0   1.6
4      2019      1    1     4  0.3  456.0  0.026   20.0  28.0   1.5
...     ...    ...  ...   ...  ...    ...    ...    ...   ...   ...
52579  2014     12   31    19  0.4  763.0  0.036   25.0  41.0   NaN
52580  2014     12   31    20  0.5  735.0  0.035   12.0  31.0   NaN
52581  2014     12   31    21  0.5  678.0  0.034   24.0  39.0   NaN
52582  2014     12   31    22  0.5  661.0  0.033   25.0  47.0   NaN
52583  2014     12   31    23  0.4  581.0  0.028   27.0  39.0   NaN

[52584 rows x 10 columns]

In [4]:
preprocessing(s2w)

0.4620918843283655
0.19657892474884806
0.1
1.8
0.47313243274450023
0.18687842842125224
0.1
1.8
0.4094708810929845
0.1673103033333731
0.1
1.3
0.378013087447961
0.1670205416205621
0.1
1.5
0.44908166801434124
0.141647945255783
0.1
1.5

551.08050255933
205.33925341419027
1.0
1214.0
612.1686970646247
144.56720194342856
398.0
1466.0
608.3642068564787
146.5499855128003
376.0
1221.0
576.8709526044111
122.49879188147548
371.0
1125.0
571.0598102730218
118.20472324819418
394.0
1137.0

0.03566875798768405
0.013193295737152208
0.001
0.1
0.04130563971102265
0.014950282002259641
0.003
0.12
0.04357867193859711
0.016180889427068995
0.001
0.134
0.03947219524040742
0.016683389179797913
0.001
0.121
0.03807427117075385
0.015086737986368844
0.003
0.11

47.977222026535166
28.803266829001718
1.0
644.0
44.5087453358209
19.042016896200796
1.0
250.0
40.06800654358495
16.416835719946285
3.0
197.0
39.09887881679389
25.221081458842956
4.0
985.0
38.76135703497153
17.409003908187138
2.0
293.0

27.944502862483937
16.037948099880477
1.0
403.0
28.80919674039581
37.474608586056235
1.0
985.0
23.710857409133272
15.711419250734819
1.0
985.0
24.423923331755798
39.8184587046665
1.0
985.0
20.63126089482859
11.520275976713702
1.0
163.0

nan
nan
nan
nan
5.624753309265936
2.738786770084951
0.1
88.7
6.57788202181305
3.723862362812964
0.1
117.2
3.1479287545540386
2.073343955077657
0.1
80.4
1.8979865771812068
1.0560817971308636
0.1
17.3

In [5]:
s2w = s2w.loc[s2w['year']>=2015]
print(((((s2w['CO']==0)).sum())+(s2w['CO'].isnull().sum())) / 43824)
print(((((s2w['CO2']==0)).sum())+(s2w['CO2'].isnull().sum())) / 43824)
print(((((s2w['NO2']==0)).sum())+(s2w['NO2'].isnull().sum())) / 43824)
print(((((s2w['PM10']==0)).sum())+(s2w['PM10'].isnull().sum())) / 43824)
print(((((s2w['PM2.5']==0)).sum())+(s2w['PM2.5'].isnull().sum())) / 43824)

0.020262869660460023
0.019076305220883535
0.026309784592917124
0.026971522453450164
0.02357155896312523

In [8]:
# 파일 바꿨음 hour column => 0 -> 24로 
# because, pandas doesn't cognize and(&) grammar.

s2w = pd.read_csv('excel/서면2w_.csv', encoding = 'cp949')
s2w = s2w.loc[s2w['year']>=2015]
# s2w = s2w.drop(['Unnamed: 0'], axis = 1)

# s1p = s1p.loc[(s1p['hour']>=5) & (s1p['hour']== 0)]

s2w_non = s2w.loc[((s2w['hour']<5))]
s2w_non
s2w_op = s2w.loc[((s2w['hour']>=5))]
s2w_op

       year  month  day  hour   CO    CO2    NO2  PM2.5  PM10  HCHO
0      2019      1    1    24  0.4  525.0  0.027   18.0  25.0   2.6
5      2019      1    1     5  0.3  497.0  0.021   23.0  30.0   1.6
6      2019      1    1     6  0.3  535.0  0.023   19.0  33.0   1.6
7      2019      1    1     7  0.3  482.0  0.026   24.0  44.0   1.6
8      2019      1    1     8  0.3  478.0  0.028   14.0  21.0   1.6
...     ...    ...  ...   ...  ...    ...    ...    ...   ...   ...
43819  2015     12   31    19  0.7  854.0  0.045   41.0  59.0   NaN
43820  2015     12   31    20  0.8  744.0  0.047   37.0  59.0   NaN
43821  2015     12   31    21  0.8  732.0  0.048   42.0  58.0   NaN
43822  2015     12   31    22  0.8  713.0  0.047   45.0  58.0   NaN
43823  2015     12   31    23  0.8  676.0  0.042   48.0  65.0   NaN

[36520 rows x 10 columns]

In [11]:
def preprocessing(df,df2):
    df = df.apply(pd.to_numeric, errors = 'coerce')
    df2 = df2.apply(pd.to_numeric, errors = 'coerce')
    
    for elements in ['CO','CO2',"NO2",'PM10','PM2.5']:
        for years in [2015, 2016, 2017,2018,2019]:
            print(df[elements].loc[(df['year']==years) & (df[elements]>0)].mean()) # 평균
            print(df[elements].loc[(df['year']==years) & (df[elements]>0)].std())  # 표준편차
            print(df2[elements].loc[(df2['year']==years) & (df2[elements]>0)].mean()) # 평균
            print(df2[elements].loc[(df2['year']==years) & (df2[elements]>0)].std())  # 표준편차
        print()
preprocessing(s2w_non,s2w_op)

0.4016973125884022
0.18956486555212687
0.47401563808992947
0.1957566574492355
0.4010380622837359
0.16082466430862633
0.48756929046564423
0.18839327400466055
0.35628453038673935
0.1593933098044644
0.42018361385451053
0.1668313144564417
0.33199713672154474
0.15407485247020566
0.3871860730593692
0.16799309407707985
0.4050139275766008
0.13451137465068735
0.4578451737986503
0.14140572013739902

399.23018080667595
112.56297645082522
581.5863369656329
206.22373976595526
448.9231301939058
30.04021868027336
645.0225783972126
135.94621180380628
434.9301521438451
25.714939114826983
643.3950272384411
135.5665091775447
445.1265103056148
25.977606632409813
602.9162568497962
117.1724682199381
444.40389972144845
23.14281878762021
596.2925915649279
113.21046995336233

0.024050349650349606
0.011400231260627289
0.03798369792392337
0.012272302364725785
0.02795543175487456
0.012561407287954464
0.04398838511055091
0.013918457098420668
0.029943252595155657
0.014335690180769297
0.046332820799552324
0.015102300640845398
0.028055964653902768
0.01488911970353791
0.04172622855481204
0.016085290921496704
0.02736281337047348
0.013895126717828788
0.04020824084350686
0.01439104040418153

50.95744680851064
53.56886646259136
47.38595750668355
20.570276316564684
35.30860741777467
19.76665174222918
46.348258010353995
18.349905439556697
33.671798460461865
18.089511978271048
41.35011923130874
15.752505467610726
34.67511177347243
50.03122327667203
39.94191990911673
16.61828759639181
30.19971771347918
16.201164773967772
40.44867872044506
17.14105912647077

30.788732394366196
23.57999025879508
27.378764532847736
13.997226943386915
30.748603351955307
65.10861482256941
28.421207041072925
28.92819945787684
22.508698677800975
13.086628583353319
23.95256751084371
16.177882752150083
30.622890682318417
91.16865720810937
23.23204965439413
16.865418349566436
19.376678445229683
12.28441332509007
20.87816411682893
11.34842087023251